### ISSUE TITLE
Добавить паддинги со всех сторон, чтобы текст не прилипал

### ISSUE THREAD

**Issue by igosheva** [aleks-va/burgers#10]
https://github.com/aleks-va/burgers/blob/86688bc1f2f83dd931787f5fe5bcf35999cd8d65/src/index.html#L182

**Comment by aleks-va** [comment]
исправил:

.menu-accord__content-text {
    position: relative;
    width: rem(470);
    height: 100%;
    @include padding($top: rem(60), $bottom: rem(60), $right: rem(20), $left: rem(20));
    line-height: 1.5;
    z-index: 10;
}
