### ISSUE TITLE
Убрать у этого элемента маржин сверху и передать как паддинг верхний для reviews__content. И вообще все маржины боковые для элементов внутри reviews__content передать элементу reviews__content как  паддинги

### ISSUE THREAD

**Issue by igosheva** [aleks-va/burgers#11]
https://github.com/aleks-va/burgers/blob/86688bc1f2f83dd931787f5fe5bcf35999cd8d65/src/index.html#L237

**Comment by aleks-va** [comment]
исправил:
.reviews__content {
    width: 100%;
    height: 100%;
    @include padding($top: rem(48), $left: rem(22), $right: rem(22))
    opacity: 0;
    transition: opacity;
    transition-duration: 1s;

    @include tablets {
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
        transform: translate(0, rem(5));
        @include padding($top: rem(48), $left: rem(44), $right: rem(44));
    }
}
