### ISSUE TITLE
Бургер должен быть полностью кликабельным. Сейчас части между полосами не кликабельны. Посмотри через консоль сколько этот элемент занимает места. Он должен покрывать полностью бургер

### ISSUE THREAD

**Issue by igosheva** [aleks-va/burgers#8]
https://github.com/aleks-va/burgers/blob/86688bc1f2f83dd931787f5fe5bcf35999cd8d65/src/index.html#L45

**Comment by aleks-va** [comment]
сделано:
<a href="#" class="header__burger-button">
     <div class="header__spacer"></div>
</a>

.header__spacer {
    position: absolute;
    top: 50%;
    left: 0;
    width: rem(25);
    height: rem(25);
    transform: translate(0, -50%);
    background: transparent;
}
