### ISSUE TITLE
Этот блок не должен быть выровнен по вертикале и горизонтале по центру, он как раз должен быть выравнен по вертикале на всех разрешениях сверху. И по на десктопе по горизонтале должен быть выравнен по левому краю, а на других разрешениях по центру http://joxi.ru/eAONKd5U4Wxex2

### ISSUE THREAD

**Issue by igosheva** [aleks-va/burgers#9]
https://github.com/aleks-va/burgers/blob/86688bc1f2f83dd931787f5fe5bcf35999cd8d65/src/index.html#L109

**Comment by igosheva** [comment]
Это потому что аккордеон будет открываться/закрываться, соответственно будет меняться значение высоты этого блока, и если выровнить его по центру, тогда контент будет скакать вверх/вниз))

**Comment by aleks-va** [comment]
исправил
